/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Teams */
        get: operations["list_teams_teams_get"];
        put?: never;
        /** Create Team */
        post: operations["create_team_teams_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Team */
        get: operations["get_team_teams__team_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Games */
        get: operations["list_games_games_get"];
        put?: never;
        /** Schedule Game */
        post: operations["schedule_game_games_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Game */
        get: operations["get_game_games__game_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record Score */
        put: operations["record_score_games__game_id__score_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Player */
        post: operations["register_player_players_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/players/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Player */
        get: operations["get_player_players__player_id__get"];
        /** Update Player */
        put: operations["update_player_players__player_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{team_id}/players": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Team Players */
        get: operations["list_team_players_teams__team_id__players_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/team-stats/{team_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record Team Stats */
        put: operations["record_team_stats_games__game_id__team_stats__team_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/player-stats/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Record Player Stats */
        put: operations["record_player_stats_games__game_id__player_stats__player_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Game Stats */
        get: operations["game_stats_games__game_id__stats_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/absences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Absences */
        get: operations["list_absences_games__game_id__absences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/absences/{player_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Report Absence */
        put: operations["report_absence_games__game_id__absences__player_id__put"];
        post?: never;
        /** Clear Absence */
        delete: operations["clear_absence_games__game_id__absences__player_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predict Week */
        get: operations["predict_week_predictions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/prediction": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Predict Game */
        get: operations["predict_game_games__game_id__prediction_get"];
        put?: never;
        /** Record Prediction */
        post: operations["record_prediction_games__game_id__prediction_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/prediction/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prediction History */
        get: operations["prediction_history_games__game_id__prediction_history_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/games/{game_id}/preview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Preview Game */
        get: operations["preview_game_games__game_id__preview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/highlights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Season Highlights */
        get: operations["season_highlights_highlights_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/calibration": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Calibration */
        get: operations["get_calibration_calibration_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AbsenceImpactRead */
        AbsenceImpactRead: {
            player: components["schemas"]["PlayerRead"];
            status: components["schemas"]["AbsenceStatus"];
            /**
             * Affected Team Id
             * Format: uuid
             */
            affected_team_id: string;
            /** Points Delta */
            points_delta: number;
        };
        /** AbsencePayload */
        AbsencePayload: {
            status: components["schemas"]["AbsenceStatus"];
        };
        /** AbsenceRead */
        AbsenceRead: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            status: components["schemas"]["AbsenceStatus"];
        };
        /**
         * AbsenceStatus
         * @enum {string}
         */
        AbsenceStatus: "OUT" | "DOUBTFUL" | "QUESTIONABLE";
        /** CalibrationParametersRead */
        CalibrationParametersRead: {
            /** Shrinkage Games */
            shrinkage_games: number;
            /** Home Field Advantage */
            home_field_advantage: number;
            /** Score Margin Stddev */
            score_margin_stddev: number;
        };
        /** CalibrationRead */
        CalibrationRead: {
            /** Season */
            season: number;
            parameters: components["schemas"]["CalibrationParametersRead"];
            backtest: components["schemas"]["CalibrationReportRead"] | null;
            /** Live */
            live: components["schemas"]["LiveCalibrationRead"][];
        };
        /** CalibrationReportRead */
        CalibrationReportRead: {
            /** Forecasts */
            forecasts: number;
            /** Brier Score */
            brier_score: number;
            /** Log Loss */
            log_loss: number;
            /** Favorite Accuracy */
            favorite_accuracy: number;
            /** Reliability */
            reliability: components["schemas"]["ReliabilityBinRead"][];
        };
        /**
         * Conference
         * @enum {string}
         */
        Conference: "AFC" | "NFC";
        /**
         * Division
         * @enum {string}
         */
        Division: "EAST" | "NORTH" | "SOUTH" | "WEST";
        /**
         * ErrorCode
         * @enum {string}
         */
        ErrorCode: "validation_error" | "team_not_in_game" | "not_found" | "schedule_conflict" | "insufficient_data" | "preview_unavailable" | "game_not_started" | "conflict";
        /** ErrorResponse */
        ErrorResponse: {
            /** Detail */
            detail: string;
            code: components["schemas"]["ErrorCode"];
        };
        /** GameCreate */
        GameCreate: {
            /** Season */
            season: number;
            /** Week */
            week: number;
            /**
             * Kickoff
             * Format: date-time
             */
            kickoff: string;
            /**
             * Home Team Id
             * Format: uuid
             */
            home_team_id: string;
            /**
             * Away Team Id
             * Format: uuid
             */
            away_team_id: string;
        };
        /** GameRead */
        GameRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Season */
            season: number;
            /** Week */
            week: number;
            /**
             * Kickoff
             * Format: date-time
             */
            kickoff: string;
            /**
             * Home Team Id
             * Format: uuid
             */
            home_team_id: string;
            /**
             * Away Team Id
             * Format: uuid
             */
            away_team_id: string;
            status: components["schemas"]["GameStatus"];
            score: components["schemas"]["ScoreRead"] | null;
        };
        /** GameStatsRead */
        GameStatsRead: {
            /** Team Stats */
            team_stats: components["schemas"]["TeamStatsRead"][];
            /** Player Stats */
            player_stats: components["schemas"]["PlayerStatsRead"][];
        };
        /**
         * GameStatus
         * @enum {string}
         */
        GameStatus: "SCHEDULED" | "FINAL";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HighlightsRead */
        HighlightsRead: {
            /** Season */
            season: number;
            /** Passing Touchdowns */
            passing_touchdowns: components["schemas"]["PlayerSeasonRead"][];
            /** Yards Per Carry */
            yards_per_carry: components["schemas"]["PlayerSeasonRead"][];
            /** Sacks */
            sacks: components["schemas"]["PlayerSeasonRead"][];
        };
        /** LiveCalibrationRead */
        LiveCalibrationRead: {
            /** Model Version */
            model_version: string;
            report: components["schemas"]["CalibrationReportRead"];
        };
        /** MatchupPreview */
        MatchupPreview: {
            /** Headline */
            headline: string;
            /** Summary */
            summary: string;
            /** Key Factors */
            key_factors: string[];
            /** Players To Watch */
            players_to_watch?: string[];
        };
        /** PlayerPayload */
        PlayerPayload: {
            /** Name */
            name: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            position: components["schemas"]["Position"];
        };
        /** PlayerRead */
        PlayerRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            position: components["schemas"]["Position"];
        };
        /** PlayerSeasonRead */
        PlayerSeasonRead: {
            player: components["schemas"]["PlayerRead"];
            /** Games */
            games: number;
            /** Passing Touchdowns */
            passing_touchdowns: number;
            /** Rushing Attempts */
            rushing_attempts: number;
            /** Rushing Yards */
            rushing_yards: number;
            /** Yards Per Carry */
            yards_per_carry: number | null;
            /** Sacks */
            sacks: number;
        };
        /** PlayerStatsPayload */
        PlayerStatsPayload: {
            /**
             * Passing Completions
             * @default 0
             */
            passing_completions: number;
            /**
             * Passing Attempts
             * @default 0
             */
            passing_attempts: number;
            /**
             * Passing Yards
             * @default 0
             */
            passing_yards: number;
            /**
             * Passing Touchdowns
             * @default 0
             */
            passing_touchdowns: number;
            /**
             * Interceptions Thrown
             * @default 0
             */
            interceptions_thrown: number;
            /**
             * Rushing Attempts
             * @default 0
             */
            rushing_attempts: number;
            /**
             * Rushing Yards
             * @default 0
             */
            rushing_yards: number;
            /**
             * Rushing Touchdowns
             * @default 0
             */
            rushing_touchdowns: number;
            /**
             * Receiving Targets
             * @default 0
             */
            receiving_targets: number;
            /**
             * Receptions
             * @default 0
             */
            receptions: number;
            /**
             * Receiving Yards
             * @default 0
             */
            receiving_yards: number;
            /**
             * Receiving Touchdowns
             * @default 0
             */
            receiving_touchdowns: number;
            /**
             * Fumbles
             * @default 0
             */
            fumbles: number;
            /**
             * Fumbles Lost
             * @default 0
             */
            fumbles_lost: number;
            /**
             * Tackles
             * @default 0
             */
            tackles: number;
            /**
             * Tackles For Loss
             * @default 0
             */
            tackles_for_loss: number;
            /**
             * Sacks
             * @default 0
             */
            sacks: number;
            /**
             * Passes Defended
             * @default 0
             */
            passes_defended: number;
            /**
             * Interceptions
             * @default 0
             */
            interceptions: number;
            /**
             * Defensive Touchdowns
             * @default 0
             */
            defensive_touchdowns: number;
            /**
             * Field Goals Made
             * @default 0
             */
            field_goals_made: number;
            /**
             * Field Goals Attempted
             * @default 0
             */
            field_goals_attempted: number;
            /**
             * Extra Points Made
             * @default 0
             */
            extra_points_made: number;
            /**
             * Extra Points Attempted
             * @default 0
             */
            extra_points_attempted: number;
            /**
             * Punts
             * @default 0
             */
            punts: number;
            /**
             * Punt Yards
             * @default 0
             */
            punt_yards: number;
            /**
             * Kick Returns
             * @default 0
             */
            kick_returns: number;
            /**
             * Kick Return Yards
             * @default 0
             */
            kick_return_yards: number;
            /**
             * Kick Return Touchdowns
             * @default 0
             */
            kick_return_touchdowns: number;
            /**
             * Punt Returns
             * @default 0
             */
            punt_returns: number;
            /**
             * Punt Return Yards
             * @default 0
             */
            punt_return_yards: number;
            /**
             * Punt Return Touchdowns
             * @default 0
             */
            punt_return_touchdowns: number;
        };
        /** PlayerStatsRead */
        PlayerStatsRead: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /**
             * Player Id
             * Format: uuid
             */
            player_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /** Passing Completions */
            passing_completions: number;
            /** Passing Attempts */
            passing_attempts: number;
            /** Passing Yards */
            passing_yards: number;
            /** Passing Touchdowns */
            passing_touchdowns: number;
            /** Interceptions Thrown */
            interceptions_thrown: number;
            /** Rushing Attempts */
            rushing_attempts: number;
            /** Rushing Yards */
            rushing_yards: number;
            /** Rushing Touchdowns */
            rushing_touchdowns: number;
            /** Receiving Targets */
            receiving_targets: number;
            /** Receptions */
            receptions: number;
            /** Receiving Yards */
            receiving_yards: number;
            /** Receiving Touchdowns */
            receiving_touchdowns: number;
            /** Fumbles */
            fumbles: number;
            /** Fumbles Lost */
            fumbles_lost: number;
            /** Tackles */
            tackles: number;
            /** Tackles For Loss */
            tackles_for_loss: number;
            /** Sacks */
            sacks: number;
            /** Passes Defended */
            passes_defended: number;
            /** Interceptions */
            interceptions: number;
            /** Defensive Touchdowns */
            defensive_touchdowns: number;
            /** Field Goals Made */
            field_goals_made: number;
            /** Field Goals Attempted */
            field_goals_attempted: number;
            /** Extra Points Made */
            extra_points_made: number;
            /** Extra Points Attempted */
            extra_points_attempted: number;
            /** Punts */
            punts: number;
            /** Punt Yards */
            punt_yards: number;
            /** Kick Returns */
            kick_returns: number;
            /** Kick Return Yards */
            kick_return_yards: number;
            /** Kick Return Touchdowns */
            kick_return_touchdowns: number;
            /** Punt Returns */
            punt_returns: number;
            /** Punt Return Yards */
            punt_return_yards: number;
            /** Punt Return Touchdowns */
            punt_return_touchdowns: number;
            /** Yards Per Carry */
            yards_per_carry: number | null;
            /** Yards Per Reception */
            yards_per_reception: number | null;
        };
        /**
         * Position
         * @enum {string}
         */
        Position: "QB" | "RB" | "WR" | "TE" | "OL" | "DL" | "EDGE" | "LB" | "CB" | "S" | "K" | "P";
        /** PredictionRead */
        PredictionRead: {
            game: components["schemas"]["GameRead"];
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Spread */
            spread: number;
            home: components["schemas"]["SideRead"];
            away: components["schemas"]["SideRead"];
            /** Absences */
            absences: components["schemas"]["AbsenceImpactRead"][];
        };
        /** PreviewRead */
        PreviewRead: {
            prediction: components["schemas"]["PredictionRead"];
            preview: components["schemas"]["MatchupPreview"];
        };
        /** RatingRead */
        RatingRead: {
            /** Games Played */
            games_played: number;
            /** Points For Avg */
            points_for_avg: number;
            /** Points Against Avg */
            points_against_avg: number;
            /** Offense Strength */
            offense_strength: number;
            /** Defense Strength */
            defense_strength: number;
        };
        /** ReliabilityBinRead */
        ReliabilityBinRead: {
            /** Lower */
            lower: number;
            /** Upper */
            upper: number;
            /** Forecasts */
            forecasts: number;
            /** Mean Probability */
            mean_probability: number;
            /** Observed Rate */
            observed_rate: number;
        };
        /** ScorePayload */
        ScorePayload: {
            /** Home */
            home: number;
            /** Away */
            away: number;
        };
        /** ScoreRead */
        ScoreRead: {
            /** Home */
            home: number;
            /** Away */
            away: number;
        };
        /** SideRead */
        SideRead: {
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /** Projected Points */
            projected_points: number;
            /** Win Probability */
            win_probability: number;
            rating: components["schemas"]["RatingRead"];
        };
        /** SnapshotRead */
        SnapshotRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /**
             * As Of
             * Format: date-time
             */
            as_of: string;
            /** Home Projected Points */
            home_projected_points: number;
            /** Away Projected Points */
            away_projected_points: number;
            /** Home Win Probability */
            home_win_probability: number;
            /** Away Win Probability */
            away_win_probability: number;
            /** Projected Spread */
            projected_spread: number;
            /** Model Version */
            model_version: string;
        };
        /** TeamCreate */
        TeamCreate: {
            /** Name */
            name: string;
            /** Abbreviation */
            abbreviation: string;
            conference: components["schemas"]["Conference"];
            division: components["schemas"]["Division"];
        };
        /** TeamRead */
        TeamRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Name */
            name: string;
            /** Abbreviation */
            abbreviation: string;
            conference: components["schemas"]["Conference"];
            division: components["schemas"]["Division"];
        };
        /** TeamStatsPayload */
        TeamStatsPayload: {
            /** Offensive Plays */
            offensive_plays: number;
            /** Passing Yards */
            passing_yards: number;
            /** Rushing Yards */
            rushing_yards: number;
            /** Turnovers */
            turnovers: number;
            /** Sacks */
            sacks: number;
        };
        /** TeamStatsRead */
        TeamStatsRead: {
            /**
             * Game Id
             * Format: uuid
             */
            game_id: string;
            /**
             * Team Id
             * Format: uuid
             */
            team_id: string;
            /** Offensive Plays */
            offensive_plays: number;
            /** Passing Yards */
            passing_yards: number;
            /** Rushing Yards */
            rushing_yards: number;
            /** Turnovers */
            turnovers: number;
            /** Sacks */
            sacks: number;
            /** Total Yards */
            total_yards: number;
            /** Yards Per Play */
            yards_per_play: number | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    list_teams_teams_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"][];
                };
            };
        };
    };
    create_team_teams_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_team_teams__team_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_games_games_get: {
        parameters: {
            query: {
                season: number;
                week?: number | null;
                team_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRead"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    schedule_game_games_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GameCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRead"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_game_games__game_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_score_games__game_id__score_put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScorePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_player_players_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_player_players__player_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_player_players__player_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                player_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_team_players_teams__team_id__players_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                team_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerRead"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_team_stats_games__game_id__team_stats__team_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                team_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TeamStatsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamStatsRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_player_stats_games__game_id__player_stats__player_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                player_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayerStatsPayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlayerStatsRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    game_stats_games__game_id__stats_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStatsRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_absences_games__game_id__absences_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceRead"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_absence_games__game_id__absences__player_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                player_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AbsencePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AbsenceRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_absence_games__game_id__absences__player_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
                player_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_week_predictions_get: {
        parameters: {
            query: {
                season: number;
                week: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionRead"][];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    predict_game_games__game_id__prediction_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_prediction_games__game_id__prediction_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    prediction_history_games__game_id__prediction_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SnapshotRead"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    preview_game_games__game_id__preview_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PreviewRead"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Conflict */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    season_highlights_highlights_get: {
        parameters: {
            query: {
                season: number;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HighlightsRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_calibration_calibration_get: {
        parameters: {
            query: {
                season: number;
                shrinkage_games?: number | null;
                home_field_advantage?: number | null;
                score_margin_stddev?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CalibrationRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
