"""expand player game stats with the full box score

Revision ID: 939b59a16449
Revises: 46fbcd2840f7
Create Date: 2026-09-19 16:34:36.629484

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "939b59a16449"
down_revision: str | Sequence[str] | None = "46fbcd2840f7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "player_game_stats",
        sa.Column(
            "passing_completions", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("passing_attempts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("passing_yards", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "interceptions_thrown", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "rushing_touchdowns", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "receiving_targets", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("receptions", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("receiving_yards", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "receiving_touchdowns", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("fumbles", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("fumbles_lost", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("tackles", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("tackles_for_loss", sa.Float(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("passes_defended", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("interceptions", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "defensive_touchdowns", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("field_goals_made", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "field_goals_attempted", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "extra_points_made", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "extra_points_attempted", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("punts", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("punt_yards", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("kick_returns", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "kick_return_yards", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "kick_return_touchdowns", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column("punt_returns", sa.Integer(), nullable=False, server_default="0"),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "punt_return_yards", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    op.add_column(
        "player_game_stats",
        sa.Column(
            "punt_return_touchdowns", sa.Integer(), nullable=False, server_default="0"
        ),
    )
    # ### end Alembic commands ###
    for column in (
        "passing_completions",
        "passing_attempts",
        "interceptions_thrown",
        "rushing_touchdowns",
        "receiving_targets",
        "receptions",
        "receiving_touchdowns",
        "fumbles",
        "fumbles_lost",
        "tackles",
        "tackles_for_loss",
        "passes_defended",
        "interceptions",
        "defensive_touchdowns",
        "field_goals_made",
        "field_goals_attempted",
        "extra_points_made",
        "extra_points_attempted",
        "punts",
        "kick_returns",
        "kick_return_touchdowns",
        "punt_returns",
        "punt_return_touchdowns",
    ):
        op.create_check_constraint(
            f"ck_player_game_stats_{column}_non_negative",
            "player_game_stats",
            f"{column} >= 0",
        )
    op.create_check_constraint(
        "ck_player_game_stats_half_tackles_for_loss",
        "player_game_stats",
        "tackles_for_loss * 2 = floor(tackles_for_loss * 2)",
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("player_game_stats", "punt_return_touchdowns")
    op.drop_column("player_game_stats", "punt_return_yards")
    op.drop_column("player_game_stats", "punt_returns")
    op.drop_column("player_game_stats", "kick_return_touchdowns")
    op.drop_column("player_game_stats", "kick_return_yards")
    op.drop_column("player_game_stats", "kick_returns")
    op.drop_column("player_game_stats", "punt_yards")
    op.drop_column("player_game_stats", "punts")
    op.drop_column("player_game_stats", "extra_points_attempted")
    op.drop_column("player_game_stats", "extra_points_made")
    op.drop_column("player_game_stats", "field_goals_attempted")
    op.drop_column("player_game_stats", "field_goals_made")
    op.drop_column("player_game_stats", "defensive_touchdowns")
    op.drop_column("player_game_stats", "interceptions")
    op.drop_column("player_game_stats", "passes_defended")
    op.drop_column("player_game_stats", "tackles_for_loss")
    op.drop_column("player_game_stats", "tackles")
    op.drop_column("player_game_stats", "fumbles_lost")
    op.drop_column("player_game_stats", "fumbles")
    op.drop_column("player_game_stats", "receiving_touchdowns")
    op.drop_column("player_game_stats", "receiving_yards")
    op.drop_column("player_game_stats", "receptions")
    op.drop_column("player_game_stats", "receiving_targets")
    op.drop_column("player_game_stats", "rushing_touchdowns")
    op.drop_column("player_game_stats", "interceptions_thrown")
    op.drop_column("player_game_stats", "passing_yards")
    op.drop_column("player_game_stats", "passing_attempts")
    op.drop_column("player_game_stats", "passing_completions")
    # ### end Alembic commands ###
