"""create initial schema

Revision ID: d3d13568c0f2
Revises:
Create Date: 2026-09-18 23:06:30.240413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d3d13568c0f2"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "teams",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("abbreviation", sa.String(length=4), nullable=False),
        sa.Column(
            "conference",
            sa.Enum(
                "AFC",
                "NFC",
                name="conference",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column(
            "division",
            sa.Enum(
                "EAST",
                "NORTH",
                "SOUTH",
                "WEST",
                name="division",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_teams")),
        sa.UniqueConstraint("abbreviation", name=op.f("uq_teams_abbreviation")),
    )
    op.create_table(
        "games",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("season", sa.Integer(), nullable=False),
        sa.Column("week", sa.Integer(), nullable=False),
        sa.Column("kickoff", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_team_id", sa.Uuid(), nullable=False),
        sa.Column("away_team_id", sa.Uuid(), nullable=False),
        sa.Column("home_score", sa.Integer(), nullable=True),
        sa.Column("away_score", sa.Integer(), nullable=True),
        sa.CheckConstraint(
            "(home_score IS NULL) = (away_score IS NULL)",
            name=op.f("ck_games_complete_score"),
        ),
        sa.CheckConstraint(
            "away_score >= 0", name=op.f("ck_games_away_score_non_negative")
        ),
        sa.CheckConstraint(
            "home_score >= 0", name=op.f("ck_games_home_score_non_negative")
        ),
        sa.CheckConstraint(
            "home_team_id <> away_team_id", name=op.f("ck_games_distinct_teams")
        ),
        sa.CheckConstraint("week BETWEEN 1 AND 22", name=op.f("ck_games_week_range")),
        sa.ForeignKeyConstraint(
            ["away_team_id"], ["teams.id"], name=op.f("fk_games_away_team_id_teams")
        ),
        sa.ForeignKeyConstraint(
            ["home_team_id"], ["teams.id"], name=op.f("fk_games_home_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_games")),
        sa.UniqueConstraint(
            "season",
            "week",
            "away_team_id",
            name=op.f("uq_games_season_week_away_team_id"),
        ),
        sa.UniqueConstraint(
            "season",
            "week",
            "home_team_id",
            name=op.f("uq_games_season_week_home_team_id"),
        ),
    )
    op.create_index("ix_games_season_week", "games", ["season", "week"], unique=False)
    op.create_table(
        "players",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column(
            "position",
            sa.Enum(
                "QB",
                "RB",
                "WR",
                "TE",
                "OL",
                "DL",
                "EDGE",
                "LB",
                "CB",
                "S",
                "K",
                "P",
                name="position",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_players_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_players")),
    )
    op.create_index(op.f("ix_players_team_id"), "players", ["team_id"], unique=False)
    op.create_table(
        "absences",
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "OUT",
                "DOUBTFUL",
                "QUESTIONABLE",
                name="absencestatus",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_absences_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"], ["players.id"], name=op.f("fk_absences_player_id_players")
        ),
        sa.PrimaryKeyConstraint("game_id", "player_id", name=op.f("pk_absences")),
    )
    op.create_table(
        "player_game_stats",
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("player_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("passing_touchdowns", sa.Integer(), nullable=False),
        sa.Column("rushing_attempts", sa.Integer(), nullable=False),
        sa.Column("rushing_yards", sa.Integer(), nullable=False),
        sa.Column("sacks", sa.Float(), nullable=False),
        sa.CheckConstraint(
            "passing_touchdowns >= 0",
            name=op.f("ck_player_game_stats_passing_touchdowns_non_negative"),
        ),
        sa.CheckConstraint(
            "rushing_attempts >= 0",
            name=op.f("ck_player_game_stats_rushing_attempts_non_negative"),
        ),
        sa.CheckConstraint(
            "sacks * 2 = floor(sacks * 2)", name=op.f("ck_player_game_stats_half_sacks")
        ),
        sa.CheckConstraint(
            "sacks >= 0", name=op.f("ck_player_game_stats_sacks_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_player_game_stats_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["player_id"],
            ["players.id"],
            name=op.f("fk_player_game_stats_player_id_players"),
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_player_game_stats_team_id_teams")
        ),
        sa.PrimaryKeyConstraint(
            "game_id", "player_id", name=op.f("pk_player_game_stats")
        ),
    )
    op.create_index(
        op.f("ix_player_game_stats_team_id"),
        "player_game_stats",
        ["team_id"],
        unique=False,
    )
    op.create_table(
        "prediction_snapshots",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("as_of", sa.DateTime(timezone=True), nullable=False),
        sa.Column("home_projected_points", sa.Float(), nullable=False),
        sa.Column("away_projected_points", sa.Float(), nullable=False),
        sa.Column("home_win_probability", sa.Float(), nullable=False),
        sa.Column("model_version", sa.String(length=32), nullable=False),
        sa.CheckConstraint(
            "away_projected_points >= 0",
            name=op.f("ck_prediction_snapshots_away_projected_points_non_negative"),
        ),
        sa.CheckConstraint(
            "home_projected_points >= 0",
            name=op.f("ck_prediction_snapshots_home_projected_points_non_negative"),
        ),
        sa.CheckConstraint(
            "home_win_probability BETWEEN 0 AND 1",
            name=op.f("ck_prediction_snapshots_probability_range"),
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_prediction_snapshots_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_prediction_snapshots")),
    )
    op.create_index(
        "ix_prediction_snapshots_game_id_as_of",
        "prediction_snapshots",
        ["game_id", "as_of"],
        unique=False,
    )
    op.create_table(
        "team_game_stats",
        sa.Column("game_id", sa.Uuid(), nullable=False),
        sa.Column("team_id", sa.Uuid(), nullable=False),
        sa.Column("offensive_plays", sa.Integer(), nullable=False),
        sa.Column("passing_yards", sa.Integer(), nullable=False),
        sa.Column("rushing_yards", sa.Integer(), nullable=False),
        sa.Column("turnovers", sa.Integer(), nullable=False),
        sa.Column("sacks", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "offensive_plays >= 0",
            name=op.f("ck_team_game_stats_offensive_plays_non_negative"),
        ),
        sa.CheckConstraint(
            "sacks >= 0", name=op.f("ck_team_game_stats_sacks_non_negative")
        ),
        sa.CheckConstraint(
            "turnovers >= 0", name=op.f("ck_team_game_stats_turnovers_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["game_id"],
            ["games.id"],
            name=op.f("fk_team_game_stats_game_id_games"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["team_id"], ["teams.id"], name=op.f("fk_team_game_stats_team_id_teams")
        ),
        sa.PrimaryKeyConstraint("game_id", "team_id", name=op.f("pk_team_game_stats")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("team_game_stats")
    op.drop_index(
        "ix_prediction_snapshots_game_id_as_of", table_name="prediction_snapshots"
    )
    op.drop_table("prediction_snapshots")
    op.drop_index(op.f("ix_player_game_stats_team_id"), table_name="player_game_stats")
    op.drop_table("player_game_stats")
    op.drop_table("absences")
    op.drop_index(op.f("ix_players_team_id"), table_name="players")
    op.drop_table("players")
    op.drop_index("ix_games_season_week", table_name="games")
    op.drop_table("games")
    op.drop_table("teams")
    # ### end Alembic commands ###
